name: Cypress Tests

on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
      - name: Install Cypress
        run: npx cypress install
      - name: Run Cypress tests
        run: npx cypress run

      - name: Generate Cypress Report
        run: npm run report

      - name: Send Cypress Report via Email
        run: node sendEmail.js


