name: Cypress Tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Cypress binary
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Install dependencies
        run: npm install

      - name: Install Cypress
        run: npx cypress install

      - name: Run Cypress tests
        run: npm run cy:run

      - name: List report files
        run: ls -la cypress/reports

      - name: Check for JSON report files
        id: check_reports
        run: |
          if ls cypress/reports/*.json 1> /dev/null 2>&1; then
            echo "Reports found"
            echo "found=true" >> $GITHUB_ENV
          else
            echo "No reports found"
            echo "found=false" >> $GITHUB_ENV
          fi

      - name: Generate Cypress Report
        if: env.found == 'true'
        run: npm run cy:report

      - name: Inline CSS in Cypress Report
        if: env.found == 'true'
        run: node inlineCss.js

      - name: Configure Git
        if: env.found == 'true'
        run: |
          git config --global user.name 'Raju'
          git config --global user.email 'vraju9949@gmail.com'

      - name: Add changes
        if: env.found == 'true'
        run: git add .

      - name: Commit changes
        if: env.found == 'true'
        run: git commit -m "Commit generated Cypress reports" || echo "No changes to commit"

      - name: Push changes
        if: env.found == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push

      - name: Send Cypress Report via Email
        if: env.found == 'true'
        run: node email.js

    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
