name: End-to-end tests

on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Install Cypress
        run: npx cypress install

      - name: Run Tests
        run: npx cypress run --spec cypress/e2e/First.spec.cy.js

      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            cypress/reports/html/assets
            cypress/reports/html/index.html

  send-email:
    needs: cypress-run
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: test-results
          path: /tmp/test-results

      - name: Zip Artifact
        run: zip -r test-results.zip /tmp/test-results

      - name: Send Email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: vraju9949
          password: dqcn wnwg wwxn bdso
          from: vraju9949@gmail.com
          subject: "Cypress Test Results"
          body: "Attached are the Cypress test results."
          to: vraju9949@gmail.com
          attachments: |
            /tmp/test-results.zip
