name: End-to-end tests

on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npx cypress run
      - name: git add
        run: git add .
      - name: mail
        run: git config --global user.email "vraju9949@gmail.com"
      - name: username
        run: git config --global user.name "Uppala Raju"
      - name: git commit
        run: git commit -m "report"
      - name: git push
        run: git push

     