name: End-to-end tests

on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Install Cypress
        run: npx cypress install

      - name: Run Tests
        run: npx cypress run --spec cypress\e2e\First.spec.cy.js

      - name: Configure Git
        run: |
          git config --global user.email "vraju9949@gmail.com"
          git config --global user.name "Uppala Raju"

      - name: Commit Changes
        run: |
          git add .
          git commit -m "Add Cypress test report"
      
      - name: Push Changes
        run: git push
