name: End-to-end tests

on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Create Reports Directory
        run: mkdir -p cypress/reports

      - name: Run Cypress Tests and Generate HTML Report
        run: |
          mkdir -p cypress/reports
          npx cypress run --reporter mochawesome
          
      - name: Save Mochawesome Reports as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: mochawesome-reports
          path: cypress/reports/*.json

      - name: Debug Reports Directory
        run: ls -R cypress/reports
