name: End-to-end tests
<<<<<<< HEAD
on:
  schedule:
    - cron: '23 13 * * *'
=======
on: 
 schedule:
   - cron: '10 13 * * *'
>>>>>>> ff1e1153db0707e873426d92acc732f6887b9438
 workflow_dispatch:
jobs:
  cypress-run:
    runs-on: [self-hosted, linux, x64, docker]
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install 
      - name: Run cypress Tests
        run: npm run test
