name: End-to-end tests

on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npx cypress run 

      - name: copy test execution res
        run: |
          mkdir public
          # cp -r cypress/vedios public/vedios
          # cp -r cypress/screenshots public/screenshots
      - name: merge
        run: npm run combine:report
      - name: generate html
        run: num run generate:report
      
      - name: Deploy report 
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.ACCESS_TOKEN}}
          publish_dir: ./public
